import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ProductProvider } from "@/contextapi/ProductContex";
import { BlueprintProvider } from "@/contextapi/blueprintContext";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <BlueprintProvider>
          <ProductProvider>{children}</ProductProvider>
        </BlueprintProvider>
        <Toaster />
      </body>
    </html>
  );
}

